#!/usr/bin/env node
/**
 * Telegram User API Authentication
 *
 * One-time interactive script to generate a session string for gramjs.
 * Run: node src/telegram-auth.js
 *
 * Requires TELEGRAM_API_ID and TELEGRAM_API_HASH from https://my.telegram.org/apps
 * Saves the session string to .env as TELEGRAM_SESSION.
 */

require('dotenv').config();

const { TelegramClient } = require('telegram');
const { StringSession } = require('telegram/sessions');
const input = require('input');
const fs = require('fs');
const path = require('path');

const API_ID = parseInt(process.env.TELEGRAM_API_ID, 10);
const API_HASH = process.env.TELEGRAM_API_HASH;

if (!API_ID || !API_HASH) {
  console.error('Missing TELEGRAM_API_ID or TELEGRAM_API_HASH in .env');
  console.error('Get these from https://my.telegram.org/apps');
  process.exit(1);
}

(async () => {
  console.log('Telegram User API Authentication');
  console.log('=================================\n');

  const client = new TelegramClient(
    new StringSession(''),
    API_ID,
    API_HASH,
    { connectionRetries: 5 }
  );

  await client.start({
    phoneNumber: async () => await input.text('Phone number (with country code): '),
    password: async () => await input.text('2FA password (if enabled): '),
    phoneCode: async () => await input.text('Code from Telegram: '),
    onError: (err) => console.error('Auth error:', err.message),
  });

  const sessionString = client.session.save();

  console.log('\nAuthenticated successfully.\n');

  // Append to .env
  const envPath = path.join(__dirname, '..', '.env');
  let envContent = fs.readFileSync(envPath, 'utf8');

  if (envContent.includes('TELEGRAM_SESSION=')) {
    // Replace existing
    envContent = envContent.replace(
      /TELEGRAM_SESSION=.*/,
      `TELEGRAM_SESSION=${sessionString}`
    );
  } else {
    // Append
    envContent += `\n# Telegram User API session (generated by telegram-auth.js)\nTELEGRAM_SESSION=${sessionString}\n`;
  }

  fs.writeFileSync(envPath, envContent);
  console.log('Session saved to .env as TELEGRAM_SESSION');
  console.log('You can now run: npm run reconcile');

  await client.disconnect();
  process.exit(0);
})();
